- name: install key (zypper/yum)
  become: yes
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: write repo configuration (zypper)
  become: yes
  zypper_repository:
    name: Visual Studio Code
    description: EPEL YUM repo
    repo: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    disable_gpg_check: no
    #gpgkey: https://packages.microsoft.com/keys/microsoft.asc


- name: Add repository
  yum_repository:
    name: Visual Studio Code
    description: EPEL YUM repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    type: rpm-md
    disable_gpg_check: no
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc




